repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.47.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt


- repo: https://github.com/Yelp/detect-secrets
  rev: v1.0.1
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: package.lock.json
  
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.26.0
  hooks:
  - id: markdownlint